# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "roda-assets_manifest"
  spec.version = "0.1.1"
  spec.authors = ["Henrique F. Teixeira"]
  spec.email = ["hriqueft@gmail.com"]

  spec.summary = "A Roda plugin for serving assets with a manifest.json (such as those generated by Vite, Webpack, esbuild, etc)."
  spec.homepage = "https://github.com/henrique-ft/roda-assets_manifest"
  spec.license = "MIT"
  spec.required_ruby_version = ">= 3.0.0"
  spec.metadata["homepage_uri"] = spec.homepage
  spec.metadata["source_code_uri"] = "https://github.com/henrique-ft/roda-assets_manifest"
  spec.metadata["changelog_uri"] = "https://github.com/henrique-ft/roda-assets_manifest/blob/main/CHANGELOG.md"

  spec.require_paths = ["lib"]
  spec.files = Dir.glob("{lib}/**/*")
  spec.add_dependency "roda", "~> 3.0"

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, check out our
  # guide at: https://guides.rubygems.org/make-your-own-gem/
end
